apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ../docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  selector:
    matchLabels:
      io.kompose.service: mongo
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f ../docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/mynet: "true"
        io.kompose.service: mongo
    spec:
      containers:
      - args:
        - --nojournal
        image: javianton97/mongo
        imagePullPolicy: ""
        name: mng
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
          - name: mongo-pv
            mountPath: /mnt/data
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
  volumeClaimTemplates:
  - metadata:
      name: mongo-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "az-storage"
      resources:
        requests:
          storage: 1Gi
