version: "3"
services:
  zookeeper:
    container_name: zk
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - mynet

  kafka:
    container_name: kfk
    image: wurstmeister/kafka
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - mynet

  mongo:
    container_name: mng
    image: mongo
    command: --nojournal
    networks:
      - mynet
    ports:
      - "27017:27017"

  mongo-seed:
    image: fvilers/mongo-seed:latest
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - practica_big_data_2019/:/practica_big_data_2019
    command:
      "mongoimport --host mongo --port 27017 -d agile_data_science -c origin_dest_distances --mode upsert --file /practica_big_data_2019/data/origin_dest_distances.jsonl"
    networks:
      - mynet

  spark-master:
    container_name: spark-m
    image: javianton97/spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=spark-master"
    networks:
      - mynet
    depends_on:
      - kafka

  spark-worker-1:
    container_name: spark-w-1
    image: javianton97/spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-worker-1"
    networks:
      - mynet
    volumes:
      - practica_big_data_2019/:/practica_big_data_2019

  web:
    # Imagen para google cloud
    image: javianton97/flask-compose-gce
    # Imagen para local
    # image: javianton97/flask-compose
    ports:
      - "5000:5000"
    networks:
      - mynet
    environment:
      - PROJECT_HOME=/practica_big_data_2019
    volumes:
      - practica_big_data_2019/:/practica_big_data_2019

volumes:
  practica_big_data_2019:
  models:

networks:
  mynet:
