apiVersion: v1
kind: PersistentVolume
metadata:
 name: mongo-pv
 labels:
  type: local
spec:
 storageClassName: az-storage
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/data"
